apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-mark-done
  namespace: todo-project
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-project-markdone
              env:
                - name: API_URL
                  value: todo-project-backend-svc:8888
              image: pasiol/markdone
              imagePullPolicy: IfNotPresent
          restartPolicy: Never